---
version: "3.9"
networks:
  inception:
    driver: bridge
volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/gpasztor/Inception/srcs/requirements/wordpress/data
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/gpasztor/Inception/srcs/requirements/mariadb/data
services:
  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    init: true
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped
  wordpress:
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    init: true
    env_file:
      - .env
    networks:
      - inception
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    restart: unless-stopped
  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    init: true
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - 433:433
    depends_on:
      - wordpress
    restart: unless-stopped
