CREATE DATABASE IF NOT EXISTS \${DATABASE_NAME};
ALTER USER 'root'@'localhost' IDENTIFIED BY '\${DATABASE_ROOT}';
CREATE USER IF NOT EXISTS '\${DATABASE_USER}' IDENTIFIED BY '\${DATABASE_USER_PASS}';
GRANT ALL PRIVILEGES ON \${DATABASE_NAME}.* TO '\${DATABASE_USER}';
FLUSH PRIVILEGES;