CREATE DATABASE IF NOT EXISTS ${DATABASE_NAME};
CREATE USER IF NOT EXISTS '${DATABASE_USER}' IDENTIFIED BY '${DATABASE_USER_PWD}';
GRANT ALL PRIVILEGES ON ${DATABASE_NAME}.* TO '${DATABASE_USER}';
ALTER USER 'root'@'localhost' IDENTIFIED BY '${DATABASE_ROOT_PWD}';
FLUSH PRIVILEGES;
EXIT;